### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by jeromecovington** [guyellis/multi-level-cache#42]
It looks like we're at a solid [1.0.0](https://github.com/guyellis/multi-level-cache/blob/master/package.json#L64) version, but the latest published version on npm is [0.0.14](https://www.npmjs.com/package/multi-level-cache). It looks like there are no breaking changes noted in the [CHANGELOG](https://github.com/guyellis/multi-level-cache/blob/master/CHANGELOG.md). Is there a reason that the major release version has not been published?

**Comment by guyellis** [comment]
@jeromecovington my feeling that because it has been running in production for so long it was out of it's initial development stage and the API breaking latitude provided by the 0.x series should no longer apply and it is ready to move to 1.x which is why I made that change.

I was then waiting for a bug fix or feature before publishing the next version so I could bundle it with the version change. I should have made this statement in the CHANGELOG though. If you're looking at updating it for a PR you can add the change in the PR and I'll append my reason above as well.
